[general]
install_requires =
    flake8
name = aligned_semantic_distance

[tox]
minversion = 3.3.0
skipsdist = True
envlist = py38, py310, lint

[testenv]
deps =
    {[general]install_requires}
    -r requirements.txt
    -r requirements-dev.txt
    .
commands =
    pytest

[testenv:lint]
maxLineLength = 120
deps =
    flake8
commands =
    flake8

[flake8]
exclude =
    .tox,
    .git,
    __pycache__,
    docs/*,
    build,
    dist,
    *.pyc,
    *.egg-info,
    .cache,
    .eggs,
    env,
    .env,
    venv,
    .venv
ignore = D203, D100, D103, D202, D200, W504
import-order-style = google
max-line-length = 120
statistics = True
application-import-names = flake8

[testenv:docs]
deps =
    {[testenv]deps}
    -rdocs/requirements.txt
    -rrequirements.txt
passenv = ENV
allowlist_externals =
    echo
commands =
    sphinx-build -E -W --keep-going -c docs/source/ -b {posargs:html} docs/source/ docs/build/{posargs:html}
commands_post = echo "open docs/build/{posargs:html}/index.html"

