name: Test

on:
  push:
    branches: "all"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.10-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.10-
 
    - name: Install test dependencies
      run: python3 -m pip install -U build tox

    - name: Test the package
      run: |
        tox -e py310